name: build-test
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          path: go/src/github.com/manastalukdar/yet-another-pomodoro-timer

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Get Protocol Buffers
        run: ./scripts/get-protobuf.sh

      - name: Get google/api/annotations.proto dependencies
        run: ./scripts/get-api-deps.sh
        env:
          GOPATH: /home/runner/work/manastalukdar/go

      - name: Build
        run: make all #go build -v .
        env:
          GOPATH: /home/runner/work/manastalukdar/go
